#!/usr/bin/env bash
echo "Running configuration script generated by the Lamp..."
./configure \
  --with-optimiz-level=O2 \
  --enable-test \
  --enable-fnal \
  --enable-t2k \
  --enable-atmo \
  --enable-rwght \
  --enable-vle-extension \
  --enable-validation-tools \
  --enable-roomuhistos \
  --with-compiler=gcc \
  >& log.config
 
# libxml is challenging for the auto-finder sometimes.
#  --with-libxml2-inc=/usr/include/libxml2 \
#  --with-libxml2-lib=/usr/lib64 \
